site_name: Tutorial GuardedBox
site_description: Cómo activar la autenticación en dos pasos (2FA) en GuardedBox
site_url: https://miguelolmedomorell.github.io/guardedbox-test/

repo_url: https://github.com/miguelolmedomorell/guardedbox-test
repo_name: miguelolmedomorell/guardedbox-test
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: deep purple
      accent: purple

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - Home: index.md
